<?php
/**
 * Scandiweb_Slider
 *
 * @category    Scandiweb
 * @package     Scandiweb_Slider
 * @author      Artis Ozolins <artis@scandiweb.com>
 * @copyright   Copyright (c) 2016 Scandiweb, Ltd (http://scandiweb.com)
 */
?>
<script type="text/javascript">
    //<![CDATA[
    require(['jquery', 'Scandiweb_Slider/js/canvas-area-draw'], function($) {
        var coordinatesInput = $('#coordinates'),
            imageLocation = $('#image_location');

        coordinatesInput.attr('data-image-url', imageLocation.val())
            .canvasAreaDraw({
                imgUrl: imageLocation.val()
            });
    });
    //]]>
</script>
